[green_agent]
image = "ghcr.io/komyo-ai/agentbeats-tutorial-debate-judge:latest"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" } # Environment variables can be provided as static strings or injected by GitHub Actions like GOOGLE_API_KEY here. Check out for details.

[[participants]]
agentbeats_id = "019aceb5-3988-7cd3-a56b-50cd90c1b2bb" # Your purple agent id goes here
name = "pro_debater" # This is specific to the debate green agent
image = "ghcr.io/komyo-ai/agentbeats-tutorial-debater:latest" # Your purple agent container image refrence goes here
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" } 

[[participants]]
agentbeats_id = "019aceb5-3988-7cd3-a56b-50cd90c1b2bb" # Your purple agent id goes here
name = "con_debater"
image = "ghcr.io/komyo-ai/agentbeats-tutorial-debater:latest" # Your purple agent container image refrence goes here
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" } 

[config]
topic = "Should artificial intelligence be regulated? Check"
num_rounds = 2
